### ISSUE TITLE
Add 'duration' key-pair in _play_url data list

### ISSUE THREAD

**Issue by TimG233** [FengLiuFeseliud/pycloudmusic#4]
能否加一个duration (歌曲长度，整数，以秒为单位)在 `music._play_url` 或者 直接添加在 `music`里
P.S: 这里的music指的是`<pycloudmusic.object.music163.Music object ...`
感谢~

**Comment by FengLiuFeseliud** [comment]
这个之前想加的一直在摸鱼没加，哈哈哈

**Comment by FengLiuFeseliud** [comment]
v0.1.4.4 添加两个值  duration (秒) duration_ms (毫秒)
